export const MESSAGE_TAKEN_IN = "MESSAGE_TAKEN_IN";
export const TAKE_IN_MESSAGE = "TAKE_IN_MESSAGE";
export const ALL_FIRST_MESSAGES = "ALL_FIRST_MESSAGES";
export const MESSAGE_SET_TAKEN_IN = "MESSAGE_SET_TAKEN_IN";
