export const ALL_QUESTIONS_TAKEN_IN = "ALL_QUESTIONS_TAKEN_IN";
export const QUESTION_TAKEN_IN = "QUESTION_TAKEN_IN";
export const ANSWERED_QUESTIONS_TAKEN_IN = "ANSWERED_QUESTIONS_TAKEN_IN";
export const UNANSWERED_QUESTIONS_TAKEN_IN = "UNANSWERED_QUESTIONS_TAKEN_IN";
export const RESPONSE_TAKEN_IN = "RESPONSE_TAKEN_IN";
export const RECEIVE_UNANSWERED_QUESTION = "RECEIVE_UNANSWERED_QUESTION";
