
const QuestionConstants = {
  ALL_QUESTIONS_TAKEN_IN: "ALL_QUESTIONS_TAKEN_IN",
  QUESTION_TAKEN_IN: "QUESTION_TAKEN_IN",
  ANSWERED_QUESTIONS_TAKEN_IN: "ANSWERED_QUESTIONS_TAKEN_IN",
  UNANSWERED_QUESTIONS_TAKEN_IN: "UNANSWERED_QUESTIONS_TAKEN_IN",
  RESPONSE_TAKEN_IN: "RESPONSE_TAKEN_IN"
};

module.exports = QuestionConstants;
