
const UserConstants = {
  ALL_USERS_TAKEN_IN: "ALL_USERS_TAKEN_IN",
  ALL_USERS_FILTERED: "ALL_USERS_FILTERED",
  USER_TAKEN_IN: "USER_TAKEN_IN",
  VIEW_USER: "VIEW_USER",
  USERID_TAKEN_IN: "USERID_TAKEN_IN"
};

module.exports = UserConstants;
