# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e67f4fb145acc93bda49355f97cde452daa89437a39832550fe92d7c700aa94bb176395068020472896a8768bdd69cb850e0a2fbf0a8304c1b44e1dc915e4c5

test:
  secret_key_base: 43a228a728bf4972cd2111010a4c909f8595fbdc8ea571fec828668fd040652ab765784cc8b0c903f1916e9099e0098d8d5be003358f20fed374d7bee54cf908

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
